CREATE TABLE Team (
	id INTEGER AUTO_INCREMENT,
	team_id INTEGER,
	team VARCHAR(30),
	conference VARCHAR(10),
	division VARCHAR(30),
	wins INTEGER,
	losses INTEGER,
	confrank INTEGER,
	pts DECIMAL(4,1),
	asts DECIMAL(3,1),
	reb DECIMAL(3,1),
	opppts DECIMAL(4,1),
	ptsrank INTEGER,
	astsrank INTEGER,
	rebrank INTEGER,
	oppptsrank INTEGER,
	color VARCHAR(10),
	secondcolor VARCHAR(10),
	PRIMARY KEY (id)
);
CREATE TABLE Player (
	id INTEGER AUTO_INCREMENT,
	player_id INTEGER,
	name VARCHAR(50),
	team VARCHAR(30),
	team_id INTEGER,
	age INTEGER,
	minutes INTEGER,
	points DECIMAL(3,1),
	assists DECIMAL(3,1),
	rebounds DECIMAL(3,1),
	blocks DECIMAL(3,1),
	turnovers DECIMAL(3,1),
	steals DECIMAL(3,1),
	ft DECIMAL(3,1),
	fg DECIMAL(3,1),
	threept DECIMAL(3,1),
	gp DECIMAL(3,1),
	gs DECIMAL(3,1),
	fouls DECIMAL(3,1),
	dreb DECIMAL(3,1),
	oreb DECIMAL(3,1),
	threeptrank INTEGER,
	rebrank INTEGER,
	ptsrank INTEGER,
	effrank INTEGER,
	stlrank INTEGER,
	orebrank INTEGER,
	drebrank INTEGER,
	threepctrank INTEGER,
	astrank INTEGER,
	blkrank INTEGER,
	tovrank INTEGER,
	ftrank INTEGER,
	fgrank INTEGER,
	salary VARCHAR(30),
	PRIMARY KEY (id)
);





